#!/bin/bash
#Author: https://github.com/zeff0669
limite=$(grep "$PAM_USER" /root/usuarios.db | awk '{print $2}')
if ! [[ "$limite" =~ ^[0-9]+$ ]]; then
    limite=1
fi
if [ "$PAM_USER" = "root" ]; then
    exit 0
elif [ "$(ps -ef | grep "sshd: $PAM_USER" | grep priv | grep -v grep | wc -l)" -gt "$limite" ]; then
    exit 1
else
    exit 0
fi
